actually add `$base`
tryforge/ForgeScript pull request #177
Opened 2023-09-21 16:15 UTC by Natasquare

check commits

2023-09-23 09:38 UTC, YuzuTheNeko commented
conflicts

2023-09-23 09:53 UTC, Natasquare commented
could have merged this first before removing $editButton output smh my head

2023-09-24 09:32 UTC, YuzuTheNeko requested changes

2023-09-24 09:32 UTC, YuzuTheNeko commented on src/native/abbreviateNumber.ts
> +            ],
place this array outside, otherwise this has to be allocated on the heap every time the function is called

2023-10-10 12:19 UTC, closed without merging